version: '3.8'

services:
  xiuxian-wiki:
    build:
      target: builder
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/dev.db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    
  # 开发环境不需要 Nginx
  nginx:
    profiles:
      - disabled